chatgpt:
  accessToken: Bearer <your OpenAI token goes here>
  completions:
    maxToken: 300
    temperature: 0.0
    topP: 1.0
    url: https://api.openai.com/v1/completions
    model: text-davinci-003
  chat-completion:
    url: https://api.openai.com/v1/chat/completions
    model: gpt-3.5-turbo